version: '3.8'

services:

  postgres:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=orderDB
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: "pg_isready -U postgres"

  spring:
    image: gerschdi/fastorderbackend:1
    container_name: spring
    ports:
      - "8080:8080"
    depends_on:
      - postgres


  admin:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "80:8080"
